// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: protos/two/two.proto

package two_pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BqvTestRequest1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BqvTestRequest1) Reset() {
	*x = BqvTestRequest1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_two_two_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqvTestRequest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqvTestRequest1) ProtoMessage() {}

func (x *BqvTestRequest1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_two_two_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqvTestRequest1.ProtoReflect.Descriptor instead.
func (*BqvTestRequest1) Descriptor() ([]byte, []int) {
	return file_protos_two_two_proto_rawDescGZIP(), []int{0}
}

type BqvTestRequest2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BqvTestRequest2) Reset() {
	*x = BqvTestRequest2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_two_two_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqvTestRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqvTestRequest2) ProtoMessage() {}

func (x *BqvTestRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_two_two_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqvTestRequest2.ProtoReflect.Descriptor instead.
func (*BqvTestRequest2) Descriptor() ([]byte, []int) {
	return file_protos_two_two_proto_rawDescGZIP(), []int{1}
}

type BqvTestResponse1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BqvTestResponse1) Reset() {
	*x = BqvTestResponse1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_two_two_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqvTestResponse1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqvTestResponse1) ProtoMessage() {}

func (x *BqvTestResponse1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_two_two_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqvTestResponse1.ProtoReflect.Descriptor instead.
func (*BqvTestResponse1) Descriptor() ([]byte, []int) {
	return file_protos_two_two_proto_rawDescGZIP(), []int{2}
}

type BqvTestResponse2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BqvTestResponse2) Reset() {
	*x = BqvTestResponse2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_two_two_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqvTestResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqvTestResponse2) ProtoMessage() {}

func (x *BqvTestResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_two_two_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqvTestResponse2.ProtoReflect.Descriptor instead.
func (*BqvTestResponse2) Descriptor() ([]byte, []int) {
	return file_protos_two_two_proto_rawDescGZIP(), []int{3}
}

var File_protos_two_two_proto protoreflect.FileDescriptor

var file_protos_two_two_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x77, 0x6f, 0x2f, 0x74, 0x77, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x74, 0x77, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x42,
	0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x22, 0x11,
	0x0a, 0x0f, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x32, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x31, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x32, 0x82, 0x02, 0x0a, 0x0a, 0x42, 0x71,
	0x76, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x08, 0x42, 0x71, 0x76, 0x54,
	0x65, 0x73, 0x74, 0x31, 0x12, 0x34, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x74, 0x77, 0x6f, 0x2e, 0x42, 0x71, 0x76, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x1a, 0x35, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x74, 0x77, 0x6f,
	0x2e, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x31, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x08, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x32, 0x12,
	0x34, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x74, 0x77, 0x6f, 0x2e, 0x42, 0x71, 0x76, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x35, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x74, 0x77, 0x6f, 0x2e, 0x42, 0x71, 0x76, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22, 0x00, 0x42, 0x43,
	0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x72,
	0x6f, 0x73, 0x74, 0x2f, 0x67, 0x69, 0x72, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x77, 0x6f, 0x3b, 0x74, 0x77, 0x6f,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_two_two_proto_rawDescOnce sync.Once
	file_protos_two_two_proto_rawDescData = file_protos_two_two_proto_rawDesc
)

func file_protos_two_two_proto_rawDescGZIP() []byte {
	file_protos_two_two_proto_rawDescOnce.Do(func() {
		file_protos_two_two_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_two_two_proto_rawDescData)
	})
	return file_protos_two_two_proto_rawDescData
}

var file_protos_two_two_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_two_two_proto_goTypes = []interface{}{
	(*BqvTestRequest1)(nil),  // 0: example.multiple_package.protos.two.BqvTestRequest1
	(*BqvTestRequest2)(nil),  // 1: example.multiple_package.protos.two.BqvTestRequest2
	(*BqvTestResponse1)(nil), // 2: example.multiple_package.protos.two.BqvTestResponse1
	(*BqvTestResponse2)(nil), // 3: example.multiple_package.protos.two.BqvTestResponse2
}
var file_protos_two_two_proto_depIdxs = []int32{
	0, // 0: example.multiple_package.protos.two.BqvService.BqvTest1:input_type -> example.multiple_package.protos.two.BqvTestRequest1
	1, // 1: example.multiple_package.protos.two.BqvService.BqvTest2:input_type -> example.multiple_package.protos.two.BqvTestRequest2
	2, // 2: example.multiple_package.protos.two.BqvService.BqvTest1:output_type -> example.multiple_package.protos.two.BqvTestResponse1
	3, // 3: example.multiple_package.protos.two.BqvService.BqvTest2:output_type -> example.multiple_package.protos.two.BqvTestResponse2
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_two_two_proto_init() }
func file_protos_two_two_proto_init() {
	if File_protos_two_two_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_two_two_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqvTestRequest1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_two_two_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqvTestRequest2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_two_two_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqvTestResponse1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_two_two_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqvTestResponse2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_two_two_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_two_two_proto_goTypes,
		DependencyIndexes: file_protos_two_two_proto_depIdxs,
		MessageInfos:      file_protos_two_two_proto_msgTypes,
	}.Build()
	File_protos_two_two_proto = out.File
	file_protos_two_two_proto_rawDesc = nil
	file_protos_two_two_proto_goTypes = nil
	file_protos_two_two_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BqvServiceClient is the client API for BqvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BqvServiceClient interface {
	BqvTest1(ctx context.Context, in *BqvTestRequest1, opts ...grpc.CallOption) (*BqvTestResponse1, error)
	BqvTest2(ctx context.Context, in *BqvTestRequest2, opts ...grpc.CallOption) (*BqvTestResponse2, error)
}

type bqvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBqvServiceClient(cc grpc.ClientConnInterface) BqvServiceClient {
	return &bqvServiceClient{cc}
}

func (c *bqvServiceClient) BqvTest1(ctx context.Context, in *BqvTestRequest1, opts ...grpc.CallOption) (*BqvTestResponse1, error) {
	out := new(BqvTestResponse1)
	err := c.cc.Invoke(ctx, "/example.multiple_package.protos.two.BqvService/BqvTest1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bqvServiceClient) BqvTest2(ctx context.Context, in *BqvTestRequest2, opts ...grpc.CallOption) (*BqvTestResponse2, error) {
	out := new(BqvTestResponse2)
	err := c.cc.Invoke(ctx, "/example.multiple_package.protos.two.BqvService/BqvTest2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BqvServiceServer is the server API for BqvService service.
type BqvServiceServer interface {
	BqvTest1(context.Context, *BqvTestRequest1) (*BqvTestResponse1, error)
	BqvTest2(context.Context, *BqvTestRequest2) (*BqvTestResponse2, error)
}

// UnimplementedBqvServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBqvServiceServer struct {
}

func (*UnimplementedBqvServiceServer) BqvTest1(context.Context, *BqvTestRequest1) (*BqvTestResponse1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BqvTest1 not implemented")
}
func (*UnimplementedBqvServiceServer) BqvTest2(context.Context, *BqvTestRequest2) (*BqvTestResponse2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BqvTest2 not implemented")
}

func RegisterBqvServiceServer(s *grpc.Server, srv BqvServiceServer) {
	s.RegisterService(&_BqvService_serviceDesc, srv)
}

func _BqvService_BqvTest1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BqvTestRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BqvServiceServer).BqvTest1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.multiple_package.protos.two.BqvService/BqvTest1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BqvServiceServer).BqvTest1(ctx, req.(*BqvTestRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

func _BqvService_BqvTest2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BqvTestRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BqvServiceServer).BqvTest2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.multiple_package.protos.two.BqvService/BqvTest2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BqvServiceServer).BqvTest2(ctx, req.(*BqvTestRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

var _BqvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.multiple_package.protos.two.BqvService",
	HandlerType: (*BqvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BqvTest1",
			Handler:    _BqvService_BqvTest1_Handler,
		},
		{
			MethodName: "BqvTest2",
			Handler:    _BqvService_BqvTest2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/two/two.proto",
}
