version: "2"

run:
  go: '1.24'

linters:
  disable:
    - errcheck

issues:
  exclude-rules:
    - text: "Error: Method notfound"
      linters:
        - all
    - text: "Error: Method not Found"
      linters:
        - all

