version: "2"

run:
  go: '1.24'

linters:
  disable:
    - errcheck

exclusions:
  rules:
    - text: "Error: Method notfound"
      linters:
        - all
    - path: e2etest/testdata/test.ct
      text: "Error: Method not Found"
      linters:
        - all

