# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Pin to specific versions for stability
gem "google-protobuf", "4.0.0.rc.1"
gem "grpc", "1.34.0"
gem "grpc-tools", "1.34.0"

# Add platform-specific gems
platforms :ruby do
  gem "google-protobuf"
end
