# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "google-protobuf", "~> 4.0"

gem "grpc", "~> 1.34"
