// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.5
// source: rerost/giro/hosts.proto

package hosts_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostOptions) Reset() {
	*x = HostOptions{}
	mi := &file_rerost_giro_hosts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOptions) ProtoMessage() {}

func (x *HostOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rerost_giro_hosts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOptions.ProtoReflect.Descriptor instead.
func (*HostOptions) Descriptor() ([]byte, []int) {
	return file_rerost_giro_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *HostOptions) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostRequest) Reset() {
	*x = GetHostRequest{}
	mi := &file_rerost_giro_hosts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostRequest) ProtoMessage() {}

func (x *GetHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rerost_giro_hosts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostRequest.ProtoReflect.Descriptor instead.
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return file_rerost_giro_hosts_proto_rawDescGZIP(), []int{1}
}

func (x *GetHostRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostResponse) Reset() {
	*x = GetHostResponse{}
	mi := &file_rerost_giro_hosts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostResponse) ProtoMessage() {}

func (x *GetHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rerost_giro_hosts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostResponse.ProtoReflect.Descriptor instead.
func (*GetHostResponse) Descriptor() ([]byte, []int) {
	return file_rerost_giro_hosts_proto_rawDescGZIP(), []int{2}
}

func (x *GetHostResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var file_rerost_giro_hosts_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*HostOptions)(nil),
		Field:         50000,
		Name:          "rerost.giro.v1.host_option",
		Tag:           "bytes,50000,opt,name=host_option",
		Filename:      "rerost/giro/hosts.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional rerost.giro.v1.HostOptions host_option = 50000;
	E_HostOption = &file_rerost_giro_hosts_proto_extTypes[0]
)

var File_rerost_giro_hosts_proto protoreflect.FileDescriptor

const file_rerost_giro_hosts_proto_rawDesc = "" +
	"\n" +
	"\x17rerost/giro/hosts.proto\x12\x0ererost.giro.v1\x1a google/protobuf/descriptor.proto\"!\n" +
	"\vHostOptions\x12\x12\n" +
	"\x04host\x18\n" +
	" \x01(\tR\x04host\"3\n" +
	"\x0eGetHostRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"%\n" +
	"\x0fGetHostResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host2[\n" +
	"\vHostService\x12L\n" +
	"\aGetHost\x12\x1e.rerost.giro.v1.GetHostRequest\x1a\x1f.rerost.giro.v1.GetHostResponse\"\x00:_\n" +
	"\vhost_option\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\v2\x1b.rerost.giro.v1.HostOptionsR\n" +
	"hostOptionB-Z+github.com/rerost/giro/rerost/giro;hosts_pbb\x06proto3"

var (
	file_rerost_giro_hosts_proto_rawDescOnce sync.Once
	file_rerost_giro_hosts_proto_rawDescData []byte
)

func file_rerost_giro_hosts_proto_rawDescGZIP() []byte {
	file_rerost_giro_hosts_proto_rawDescOnce.Do(func() {
		file_rerost_giro_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rerost_giro_hosts_proto_rawDesc), len(file_rerost_giro_hosts_proto_rawDesc)))
	})
	return file_rerost_giro_hosts_proto_rawDescData
}

var file_rerost_giro_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rerost_giro_hosts_proto_goTypes = []any{
	(*HostOptions)(nil),                 // 0: rerost.giro.v1.HostOptions
	(*GetHostRequest)(nil),              // 1: rerost.giro.v1.GetHostRequest
	(*GetHostResponse)(nil),             // 2: rerost.giro.v1.GetHostResponse
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_rerost_giro_hosts_proto_depIdxs = []int32{
	3, // 0: rerost.giro.v1.host_option:extendee -> google.protobuf.ServiceOptions
	0, // 1: rerost.giro.v1.host_option:type_name -> rerost.giro.v1.HostOptions
	1, // 2: rerost.giro.v1.HostService.GetHost:input_type -> rerost.giro.v1.GetHostRequest
	2, // 3: rerost.giro.v1.HostService.GetHost:output_type -> rerost.giro.v1.GetHostResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rerost_giro_hosts_proto_init() }
func file_rerost_giro_hosts_proto_init() {
	if File_rerost_giro_hosts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rerost_giro_hosts_proto_rawDesc), len(file_rerost_giro_hosts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_rerost_giro_hosts_proto_goTypes,
		DependencyIndexes: file_rerost_giro_hosts_proto_depIdxs,
		MessageInfos:      file_rerost_giro_hosts_proto_msgTypes,
		ExtensionInfos:    file_rerost_giro_hosts_proto_extTypes,
	}.Build()
	File_rerost_giro_hosts_proto = out.File
	file_rerost_giro_hosts_proto_goTypes = nil
	file_rerost_giro_hosts_proto_depIdxs = nil
}
