# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/two/two.proto for package 'example.multiple_package.protos.two'

require 'grpc'
require 'protos/two/two_pb'

module Example
  module MultiplePackage
    module Protos
      module Two
        module BqvService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'example.multiple_package.protos.two.BqvService'

            rpc :BqvTest1, ::Example::MultiplePackage::Protos::Two::BqvTestRequest1, ::Example::MultiplePackage::Protos::Two::BqvTestResponse1
            rpc :BqvTest2, ::Example::MultiplePackage::Protos::Two::BqvTestRequest2, ::Example::MultiplePackage::Protos::Two::BqvTestResponse2
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
