# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/two/two.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/two/two.proto", :syntax => :proto3) do
    add_message "example.multiple_package.protos.two.BqvTestRequest1" do
    end
    add_message "example.multiple_package.protos.two.BqvTestRequest2" do
    end
    add_message "example.multiple_package.protos.two.BqvTestResponse1" do
    end
    add_message "example.multiple_package.protos.two.BqvTestResponse2" do
    end
  end
end

module Example
  module MultiplePackage
    module Protos
      module Two
        BqvTestRequest1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.two.BqvTestRequest1").msgclass
        BqvTestRequest2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.two.BqvTestRequest2").msgclass
        BqvTestResponse1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.two.BqvTestResponse1").msgclass
        BqvTestResponse2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.two.BqvTestResponse2").msgclass
      end
    end
  end
end
