// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: protos/hosts.proto

package hosts_pb

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HostOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *HostOptions) Reset() {
	*x = HostOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hosts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOptions) ProtoMessage() {}

func (x *HostOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hosts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOptions.ProtoReflect.Descriptor instead.
func (*HostOptions) Descriptor() ([]byte, []int) {
	return file_protos_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *HostOptions) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var file_protos_hosts_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*HostOptions)(nil),
		Field:         50000,
		Name:          "rerost.giro.hosts.host",
		Tag:           "bytes,50000,opt,name=host",
		Filename:      "protos/hosts.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// optional rerost.giro.hosts.HostOptions host = 50000;
	E_Host = &file_protos_hosts_proto_extTypes[0]
)

var File_protos_hosts_proto protoreflect.FileDescriptor

var file_protos_hosts_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x65, 0x72, 0x6f, 0x73, 0x74, 0x2e, 0x67, 0x69, 0x72,
	0x6f, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x48, 0x6f, 0x73,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x3a, 0x55, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x72, 0x65, 0x72, 0x6f, 0x73, 0x74, 0x2e, 0x67, 0x69, 0x72, 0x6f, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x73, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x65, 0x72, 0x6f, 0x73, 0x74, 0x2f, 0x67, 0x69, 0x72, 0x6f, 0x2f, 0x70, 0x62,
	0x3b, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_hosts_proto_rawDescOnce sync.Once
	file_protos_hosts_proto_rawDescData = file_protos_hosts_proto_rawDesc
)

func file_protos_hosts_proto_rawDescGZIP() []byte {
	file_protos_hosts_proto_rawDescOnce.Do(func() {
		file_protos_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_hosts_proto_rawDescData)
	})
	return file_protos_hosts_proto_rawDescData
}

var file_protos_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_hosts_proto_goTypes = []interface{}{
	(*HostOptions)(nil),               // 0: rerost.giro.hosts.HostOptions
	(*descriptor.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_protos_hosts_proto_depIdxs = []int32{
	1, // 0: rerost.giro.hosts.host:extendee -> google.protobuf.MessageOptions
	0, // 1: rerost.giro.hosts.host:type_name -> rerost.giro.hosts.HostOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_hosts_proto_init() }
func file_protos_hosts_proto_init() {
	if File_protos_hosts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_hosts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_hosts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protos_hosts_proto_goTypes,
		DependencyIndexes: file_protos_hosts_proto_depIdxs,
		MessageInfos:      file_protos_hosts_proto_msgTypes,
		ExtensionInfos:    file_protos_hosts_proto_extTypes,
	}.Build()
	File_protos_hosts_proto = out.File
	file_protos_hosts_proto_rawDesc = nil
	file_protos_hosts_proto_goTypes = nil
	file_protos_hosts_proto_depIdxs = nil
}
