// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: e2etest/dummyserver/echo.proto

package dummyserver

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/rerost/giro/rerost/giro"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_e2etest_dummyserver_echo_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataValue) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_e2etest_dummyserver_echo_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_e2etest_dummyserver_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// https://godoc.org/google.golang.org/grpc/metadata#MD
	Metadata      *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_e2etest_dummyserver_echo_proto_rawDescGZIP(), []int{3}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_e2etest_dummyserver_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_e2etest_dummyserver_echo_proto_rawDescGZIP(), []int{4}
}

func (x *EmptyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmptyResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_e2etest_dummyserver_echo_proto protoreflect.FileDescriptor

const file_e2etest_dummyserver_echo_proto_rawDesc = "" +
	"\n" +
	"\x1ee2etest/dummyserver/echo.proto\x12\x0ererost.giro.v1\x1a\x17rerost/giro/hosts.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\rMetadataValue\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\"\xaa\x01\n" +
	"\bMetadata\x12B\n" +
	"\bmetadata\x18\x01 \x03(\v2&.rerost.giro.v1.Metadata.MetadataEntryR\bmetadata\x1aZ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.rerost.giro.v1.MetadataValueR\x05value:\x028\x01\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"^\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.rerost.giro.v1.MetadataR\bmetadata\"]\n" +
	"\rEmptyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.rerost.giro.v1.MetadataR\bmetadata2\xae\x01\n" +
	"\vTestService\x12C\n" +
	"\x04Echo\x12\x1b.rerost.giro.v1.EchoRequest\x1a\x1c.rerost.giro.v1.EchoResponse\"\x00\x12D\n" +
	"\tEmptyCall\x12\x16.google.protobuf.Empty\x1a\x1d.rerost.giro.v1.EmptyResponse\"\x00\x1a\x14\x82\xb5\x18\x10R\x0elocalhost:5000B8Z6github.com/rerost/giro/e2etest/dummyserver;dummyserverb\x06proto3"

var (
	file_e2etest_dummyserver_echo_proto_rawDescOnce sync.Once
	file_e2etest_dummyserver_echo_proto_rawDescData []byte
)

func file_e2etest_dummyserver_echo_proto_rawDescGZIP() []byte {
	file_e2etest_dummyserver_echo_proto_rawDescOnce.Do(func() {
		file_e2etest_dummyserver_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_e2etest_dummyserver_echo_proto_rawDesc), len(file_e2etest_dummyserver_echo_proto_rawDesc)))
	})
	return file_e2etest_dummyserver_echo_proto_rawDescData
}

var file_e2etest_dummyserver_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_e2etest_dummyserver_echo_proto_goTypes = []any{
	(*MetadataValue)(nil), // 0: rerost.giro.v1.MetadataValue
	(*Metadata)(nil),      // 1: rerost.giro.v1.Metadata
	(*EchoRequest)(nil),   // 2: rerost.giro.v1.EchoRequest
	(*EchoResponse)(nil),  // 3: rerost.giro.v1.EchoResponse
	(*EmptyResponse)(nil), // 4: rerost.giro.v1.EmptyResponse
	nil,                   // 5: rerost.giro.v1.Metadata.MetadataEntry
	(*empty.Empty)(nil),   // 6: google.protobuf.Empty
}
var file_e2etest_dummyserver_echo_proto_depIdxs = []int32{
	5, // 0: rerost.giro.v1.Metadata.metadata:type_name -> rerost.giro.v1.Metadata.MetadataEntry
	1, // 1: rerost.giro.v1.EchoResponse.metadata:type_name -> rerost.giro.v1.Metadata
	1, // 2: rerost.giro.v1.EmptyResponse.metadata:type_name -> rerost.giro.v1.Metadata
	0, // 3: rerost.giro.v1.Metadata.MetadataEntry.value:type_name -> rerost.giro.v1.MetadataValue
	2, // 4: rerost.giro.v1.TestService.Echo:input_type -> rerost.giro.v1.EchoRequest
	6, // 5: rerost.giro.v1.TestService.EmptyCall:input_type -> google.protobuf.Empty
	3, // 6: rerost.giro.v1.TestService.Echo:output_type -> rerost.giro.v1.EchoResponse
	4, // 7: rerost.giro.v1.TestService.EmptyCall:output_type -> rerost.giro.v1.EmptyResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_e2etest_dummyserver_echo_proto_init() }
func file_e2etest_dummyserver_echo_proto_init() {
	if File_e2etest_dummyserver_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2etest_dummyserver_echo_proto_rawDesc), len(file_e2etest_dummyserver_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e2etest_dummyserver_echo_proto_goTypes,
		DependencyIndexes: file_e2etest_dummyserver_echo_proto_depIdxs,
		MessageInfos:      file_e2etest_dummyserver_echo_proto_msgTypes,
	}.Build()
	File_e2etest_dummyserver_echo_proto = out.File
	file_e2etest_dummyserver_echo_proto_goTypes = nil
	file_e2etest_dummyserver_echo_proto_depIdxs = nil
}
