# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/one/one.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/one/one.proto", :syntax => :proto3) do
    add_message "example.multiple_package.protos.one.GiroTestRequest1" do
      optional :message, :string, 1
    end
    add_message "example.multiple_package.protos.one.GiroTestRequest2" do
    end
    add_message "example.multiple_package.protos.one.GiroTestResponse1" do
      optional :message, :string, 1
    end
    add_message "example.multiple_package.protos.one.GiroTestResponse2" do
    end
  end
end

module Example
  module MultiplePackage
    module Protos
      module One
        GiroTestRequest1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.one.GiroTestRequest1").msgclass
        GiroTestRequest2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.one.GiroTestRequest2").msgclass
        GiroTestResponse1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.one.GiroTestResponse1").msgclass
        GiroTestResponse2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.multiple_package.protos.one.GiroTestResponse2").msgclass
      end
    end
  end
end
