name: Check Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_docker_build:
    runs-on: ubuntu-latest
    name: Check Docker Build
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check
      run: |
        docker build -t test ./example/multiple_package/server
