name: Check Example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_docker_build:
    runs-on: ubuntu-latest
    name: Check Docker Build
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
    - name: Build Example Binary
      run: |
        # Build the binaries once with proper caching
        go build -o bin/example_server example/multiple_package/main.go
        go build -o bin/giro cmd/giro/main.go
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: ./example/multiple_package/server
        push: false
        cache-from: |
          type=gha,scope=master
          type=gha,scope=${{ github.ref_name }}
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}
        tags: test
        load: true
    - name: Run
      run: |
        echo "docker run"
        time docker run -d -p 5001:5001 test # RPC Server
        echo "reflection server"
        ./bin/example_server & # Use pre-built binary instead of go run

        echo "check ls"
        echo -e "example.multiple_package.protos.one.GiroService\nexample.multiple_package.protos.two.BqvService\ngrpc.health.v1.Health\ngrpc.reflection.v1.ServerReflection\ngrpc.reflection.v1alpha.ServerReflection\nrerost.giro.v1.HostService" > ls_expect.txt
        ./bin/giro ls > ls_result.txt # Use pre-built binary instead of go run
        diff ls_result.txt ls_expect.txt

        echo "check call"
        echo "{\"message\":\"test\"}" > call_expect.txt
        ./bin/giro call --rpc-server=localhost:5001 example.multiple_package.protos.one.GiroService/GiroTest1 '{"message": "test"}' > call_result.txt
        diff call_result.txt call_expect.txt

  check_make_protoc:
    runs-on: ubuntu-latest
    name: Check `make protoc`
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.x"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: example/multiple_package/
    - name: Install grpc_tools_ruby_protoc
      run: gem install grpc-tools
    - name: Check
      run: cd example/multiple_package/ &&  make protoc && git diff --exit-code
